'use client'

import { useState, useTransition } from 'react'
import { useRouter } from 'next/navigation'
import { approvePayoutAction, cancelPayoutAction, createCustomerAction, createInvoiceAction, createSubscriptionAction, markInvoicePaidAction, markPayoutPaidAction, rejectPayoutAction, releaseCommissionsAction, sendInvoiceAction, setInvoiceStatusAction, setSubscriptionStatusAction, updateAffiliateStatusAction, voidCommissionAction } from '@/app/actions/affiliate-admin'

type Field = { name:string; label:string; type?:string; required?:boolean; options?:Array<{ value:string; label:string }> }
type Row = { id?: string; status?: string; invoiceId?: string; [key: string]: string | number | null | undefined }
type Action = { label:string; fields?:Field[]; run:(row:Row, values:Record<string,string>)=>Promise<{success:boolean;error?:string}>; show?:(row:Row)=>boolean }

export function AdminOperations({ title, description, rows, columns, actions = [], create }: { title:string; description:string; rows:object[]; columns:Array<{key:string;label:string;format?:'money'|'date'}>; actions?:Action[]; create?:{ label:string; fields:Field[]; run:(values:Record<string,string>)=>Promise<{success:boolean;error?:string}> } }) {
  const tableRows = rows as Row[]
  const router = useRouter(); const [pending,start] = useTransition(); const [error,setError] = useState('')
  const execute = (work:()=>Promise<{success:boolean;error?:string}>) => start(async()=>{ setError(''); const result=await work(); if(!result.success)setError(result.error??'Operasi gagal'); else router.refresh() })
  const collect = (fields:Field[]) => { const result:Record<string,string>={}; for(const field of fields){ const value=window.prompt(field.label); if(value===null)return null; result[field.name]=value } return result }
  const render = (value:string|number|null|undefined, format?:'money'|'date') => value===null?'—':format==='money'?new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(value)):format==='date'?new Date(String(value)).toLocaleDateString('id-ID'):String(value)
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="text-2xl font-extrabold">{title}</h2><p className="text-sm text-muted-foreground">{description}</p></div>{create&&<button disabled={pending} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground" onClick={()=>{const values=collect(create.fields);if(values)execute(()=>create.run(values))}}>{create.label}</button>}</div>{error&&<p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full text-left text-sm"><thead><tr className="border-b bg-muted/40">{columns.map(c=><th key={c.key} className="px-4 py-3">{c.label}</th>)}{actions.length>0&&<th className="px-4 py-3 text-right">Aksi</th>}</tr></thead><tbody>{tableRows.length===0?<tr><td colSpan={columns.length+1} className="p-8 text-center text-muted-foreground">Belum ada data.</td></tr>:tableRows.map((row,index)=><tr key={String(row.id??index)} className="border-b last:border-0">{columns.map(c=><td key={c.key} className="px-4 py-3">{render(row[c.key],c.format)}</td>)}{actions.length>0&&<td className="px-4 py-3"><div className="flex justify-end gap-2">{actions.filter(a=>!a.show||a.show(row)).map(a=><button disabled={pending} key={a.label} className="rounded border px-2 py-1 hover:bg-muted" onClick={()=>{const values=a.fields?collect(a.fields):{};if(values)execute(()=>a.run(row,values))}}>{a.label}</button>)}</div></td>}</tr>)}</tbody></table></div></div>
}

export const affiliateActions:Action[]=[{label:'Setujui',show:r=>r.status!=='active',run:r=>updateAffiliateStatusAction(String(r.id),'active')},{label:'Tangguhkan',show:r=>r.status==='active',run:r=>updateAffiliateStatusAction(String(r.id),'suspended')},{label:'Tolak',show:r=>r.status==='pending',run:r=>updateAffiliateStatusAction(String(r.id),'rejected')}]
export const customerCreate=(affiliates:Array<{id:string;name:string}>)=>({label:'Tambah pelanggan',fields:[{name:'name',label:'Nama pelanggan'},{name:'email',label:'Email pelanggan'},{name:'affiliateId',label:`ID affiliate (opsional): ${affiliates.map(a=>`${a.name}=${a.id}`).join(', ')}`},{name:'sourceId',label:'ID lead/demo untuk konversi (opsional)'}],run:(v:Record<string,string>)=>createCustomerAction({name:v.name,email:v.email,affiliateId:v.affiliateId||undefined,sourceId:v.sourceId||undefined})})
export const subscriptionCreate=(customers:Array<{id:string;name:string}>)=>({label:'Tambah subscription',fields:[{name:'customerId',label:`ID pelanggan: ${customers.map(c=>`${c.name}=${c.id}`).join(', ')}`},{name:'productCode',label:'Kode produk'},{name:'periodStart',label:'Mulai (YYYY-MM-DD)'},{name:'periodEnd',label:'Berakhir (YYYY-MM-DD)'}],run:(v:Record<string,string>)=>createSubscriptionAction(v as {customerId:string;productCode:string;periodStart:string;periodEnd:string})})
export const subscriptionActions:Action[]=[{label:'Aktifkan',show:r=>r.status!=='active',run:r=>setSubscriptionStatusAction(String(r.id),'active')},{label:'Past due',show:r=>r.status==='active',run:r=>setSubscriptionStatusAction(String(r.id),'past_due')},{label:'Batalkan',show:r=>r.status!=='cancelled',run:r=>setSubscriptionStatusAction(String(r.id),'cancelled')}]
export const invoiceCreate=(subscriptions:Array<{id:string;customerName:string}>)=>({label:'Buat invoice',fields:[{name:'subscriptionId',label:`ID subscription: ${subscriptions.map(s=>`${s.customerName}=${s.id}`).join(', ')}`},{name:'amount',label:'Jumlah rupiah'},{name:'cycleNumber',label:'Siklus ke-'},{name:'dueAt',label:'Jatuh tempo (YYYY-MM-DD)'}],run:(v:Record<string,string>)=>createInvoiceAction({subscriptionId:v.subscriptionId,amount:Number(v.amount),cycleNumber:Number(v.cycleNumber),dueAt:v.dueAt})})
export const invoiceActions:Action[]=[{label:'Kirim',show:r=>r.status==='draft'||r.status==='sent'||r.status==='overdue',run:r=>sendInvoiceAction(String(r.id))},{label:'Lunas',show:r=>r.status!=='paid'&&r.status!=='void',fields:[{name:'reference',label:'Referensi pembayaran'}],run:(r,v)=>markInvoicePaidAction(String(r.id),v.reference)},{label:'Void',show:r=>r.status!=='paid'&&r.status!=='void',run:r=>setInvoiceStatusAction(String(r.id),'void')}]
export const commissionActions:Action[]=[{label:'Void',show:r=>r.status!=='paid'&&r.status!=='void',fields:[{name:'reason',label:'Alasan void'}],run:(r,v)=>voidCommissionAction(String(r.invoiceId),v.reason)}]
export const payoutActions:Action[]=[{label:'Setujui',show:r=>r.status==='requested',run:r=>approvePayoutAction(String(r.id))},{label:'Tandai dibayar',show:r=>r.status==='requested'||r.status==='approved',fields:[{name:'reference',label:'Referensi transfer'}],run:(r,v)=>markPayoutPaidAction(String(r.id),v.reference)},{label:'Tolak',show:r=>r.status==='requested'||r.status==='approved',run:r=>rejectPayoutAction(String(r.id))},{label:'Batalkan',show:r=>r.status==='requested'||r.status==='approved',run:r=>cancelPayoutAction(String(r.id))}]
export const releaseAction={label:'Lepas komisi jatuh tempo',fields:[],run:()=>releaseCommissionsAction()}
